services:
  portofolio-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portofolio-web
    restart: unless-stopped
    ports:
      - "4782:4782"
    environment:
      - PORT=4782
      - HOST=0.0.0.0
      - NODE_ENV=production

  portofolio-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: portofolio-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflared/bede2f17-29d8-47f3-9607-fbb25e021649.json:/etc/cloudflared/bede2f17-29d8-47f3-9607-fbb25e021649.json:ro
    depends_on:
      - portofolio-web
