tunnel: bede2f17-29d8-47f3-9607-fbb25e021649
credentials-file: /etc/cloudflared/bede2f17-29d8-47f3-9607-fbb25e021649.json
protocol: http2

ingress:
  - hostname: alvnvnc.site
    service: http://portofolio-web:4782
  - service: http_status:404
